name: Docker Image CI with Node.js

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - uses: actions/checkout@v4

    # Step 2: Set up Node.js (optional, only if you need Node.js for build tasks before Docker)
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'  # Ensure Node.js 20 is used in the workflow

    # Step 3: Install dependencies (optional)
    - name: Install dependencies
      run: npm install

    # Step 4: Build the Docker image with Node.js
    - name: Build the Docker image
      run: |
        IMAGE_TAG="samcrit-client-app:$(date +%s)"  # Ensure the tag is stored in a variable
        docker build . --file Dockerfile --tag $IMAGE_TAG

    # Step 5: Debugging Step - List Docker Images to confirm it's built
    - name: List Docker images (Debugging step)
      run: docker images

    # Step 6: Run the Docker image (with the correct tag)
    - name: Run Docker container
      run: |
        IMAGE_TAG="samcrit-client-app:$(date +%s)"  # Make sure to use the same tag variable
        docker run -d -p 3000:3000 $IMAGE_TAG
