name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4  # Checkout the code

    # Build the Docker image
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag samcrit-client-app:$(date +%s)
