name: Build and Deploy Docker Container

on:
  push:
    branches:
      - main   
  pull_request:
    branches:
      - main   

jobs:
  build:
    runs-on: ubuntu-latest   # Use the latest Ubuntu runner
    
    steps:
      # Checkout the repository code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Docker Buildx (required for advanced builds)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Cache Docker layers for faster builds
      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      # Build and push the Docker image
      - name: Build Docker image
        run: |
          docker build -t your-dockerhub-username/your-repository-name:${{ github.sha }} .
      
      # Push the Docker image to Docker Hub (or any Docker registry)
      - name: Push Docker image
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push your-dockerhub-username/your-repository-name:${{ github.sha }}

      # Optional: Deploy to your cloud service (e.g., AWS, Azure, DigitalOcean) after build & push
      # Example: Deploy to AWS ECS, Docker Swarm, etc.

