name: Node.js CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger on push to main branch
  pull_request:
    branches:
      - main  # Trigger on PRs to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner
    
    steps:
      # Step 1: Checkout the repository code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js (specify the version you want)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Use Node.js 18 (or any other version)

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install  # Run npm install to install your dependencies

      # Step 4: Run tests (if you have tests set up)
      - name: Run tests
        run: npm test  # If you have tests defined in your package.json

      # Step 5: Build the application (if applicable)
      - name: Build the application
        run: npm run build  # If you have a build script

      # Step 6: Deploy the application (optional, depending on your deployment method)
      - name: Deploy the application
        run: |
          echo "Deploying the application..."
          # Example: Deploy to a server, AWS, or other service
          # If deploying to a remote server via SSH:
          # ssh -i ${{ secrets.SSH_PRIVATE_KEY }} user@your-server "deploy script"

          # Or deploy to cloud services such as AWS, Azure, or DigitalOcean
          # Example for AWS (Elastic Beanstalk, S3, etc.), make sure to use secrets for credentials
